### ISSUE TITLE
`q` key closes `magit` but leaves a scratch buffer.

### ISSUE THREAD

**Issue by utdemir** [d4ncer/magito#2]
When I press `q` to exit `magito`, the `magit` buffer closes however there's still a `scratch` buffer left on the screen, and I have to do `:q` to exit it.

I think disabling `scratch` buffer and either disabling the `q` key or making it close magito completely would be a nicer behavior.

**Comment by d4ncer** [comment]
solved with 06c7fb85255a49aa0e36743cc63e4e284184b41a
